version: "3"

services:
  client:
    build:
      context: "./client"
      dockerfile: Dockerfile

    ports:
      - 3000:3000

    container_name: client-container

    networks:
      - ielts_dash

    volumes:
      - ./client:/app

    depends_on:
      - server

  server:
    build:
      context: "./server"
      dockerfile: Dockerfile

    ports:
      - 8000:8000

    container_name: server-container

    networks:
      - ielts_dash

    volumes:
      - ./server:/app

    depends_on:
      - database

networks:
  ielts_dash:
